"""Typed translation of file-template-cad/config.py at commit 76b8d75."""

from python_cad_tools.units import FOOT, INCH, MM

PROJECT_NAME = "File Template"

UPPER_DECK_WIDTH = 24.5 * FOOT
UPPER_DECK_DEPTH = 20 * FOOT
LOWER_DECK_WIDTH = 17.5 * FOOT
LOWER_DECK_DEPTH = 19 * FOOT
LOWER_DECK_ELEVATION = 32 * INCH
UPPER_DECK_ELEVATION = LOWER_DECK_ELEVATION + 28 * INCH
DECK_THICKNESS = 6 * INCH
DECK_BOARD_WIDTH = 5.5 * INCH
DECK_BOARD_GAP = 0.25 * INCH
DECK_BOARD_THICKNESS = 1.25 * INCH
JOIST_WIDTH = 1.5 * INCH
JOIST_HEIGHT = 7.25 * INCH
JOIST_SPACING = 16 * INCH
BEAM_WIDTH = 5.5 * INCH
BEAM_HEIGHT = 11.25 * INCH
SUPPORT_POST_SIZE = 6 * INCH

ROOF_HEIGHT_ABOVE_UPPER = 9 * FOOT
ROOF_THICKNESS = 8 * INCH
ROOF_OVERHANG = 12 * INCH
ROOF_FASCIA_HEIGHT = 10 * INCH
ROOF_RAFTER_WIDTH = 2 * INCH
ROOF_RAFTER_HEIGHT = 8 * INCH
ROOF_RAFTER_SPACING = 24 * INCH
ROOF_SLOPE_DROP = 30 * INCH
ROOF_STYLE = "shed"  # shed | flat | gable
ROOF_ATTACH_TO_HOUSE = True
ROOF_FRONT_POSTS = 2

STAIR_WIDTH = 4 * FOOT
TREAD_DEPTH = 11 * INCH
MAX_RISER = 7.5 * INCH
LANDING_DEPTH = 5 * FOOT

POOL_LENGTH = 34 * FOOT
POOL_WIDTH = 12 * FOOT
POOL_SHALLOW_DEPTH = 5 * FOOT
POOL_DEEP_DEPTH = 8 * FOOT
# Deep end is on the "reverse" side (left, near the house) of the pool footprint
# and the shallow end is on the right (toward the lower deck edge).
POOL_DEEP_END_SIDE = "left"  # left | right
PATIO_BORDER = 2 * FOOT
POOL_TILE_SIZE = 2 * FOOT
DECK_TO_POOL_CLEARANCE = 6 * FOOT
GRASS_THICKNESS = 2 * INCH

HOT_TUB_WIDTH = 8 * FOOT
HOT_TUB_DEPTH = 8 * FOOT
HOT_TUB_ABOVE_DECK = 1 * FOOT

FIREPLACE_WIDTH = 4 * FOOT
FIREPLACE_DEPTH = 6 * FOOT
FIREPLACE_HEIGHT = UPPER_DECK_ELEVATION + 9 * FOOT
FIREPLACE_OPENING_WIDTH = 18 * INCH
FIREPLACE_OPENING_HEIGHT = 30 * INCH
TV_WIDTH = 48 * INCH
TV_HEIGHT = 28 * INCH

KITCHEN_LENGTH = 10 * FOOT
KITCHEN_DEPTH = 30 * INCH
KITCHEN_COUNTER_HEIGHT = 38 * INCH
KITCHEN_COUNTER_THICKNESS = 3 * INCH
KITCHEN_GRILL_WIDTH = 36 * INCH
KITCHEN_DOOR_WIDTH = 18 * INCH
KITCHEN_SINK_WIDTH = 24 * INCH
KITCHEN_SINK_DEPTH = 18 * INCH

FAN_DIAMETER = 72 * INCH
FAN_BLADE_WIDTH = 7 * INCH

HOUSE_DEPTH = 1 * INCH
HOUSE_HEIGHT = UPPER_DECK_ELEVATION + ROOF_HEIGHT_ABOVE_UPPER
HOUSE_WIDTH = UPPER_DECK_WIDTH
DOOR_WIDTH = 6 * FOOT
DOOR_HEIGHT = 7 * FOOT

SECTION_CUT_X = 4000.0 * MM

HOUSE_COLOR = (0.35, 0.43, 0.50)
DECK_COLOR = (0.45, 0.27, 0.12)
SKIRTING_COLOR = (0.23, 0.18, 0.14)
RAILING_COLOR = (0.10, 0.10, 0.10)
BRICK_COLOR = (0.55, 0.18, 0.10)
WATER_COLOR = (0.05, 0.30, 0.65)
PAVER_COLOR = (0.70, 0.70, 0.68)
TILE_COLOR = (0.78, 0.80, 0.82)
GRASS_COLOR = (0.36, 0.55, 0.24)
